### ISSUE TITLE
CLI failed to initialized

### ISSUE THREAD

**Issue by rizalrenaldi** [firelayer/firelayer#8] opened 2021-01-17 02:34 UTC
Hi, initialized from cli says: 
✖ Preparing the list of your Firebase 
projectsError: failed to get boilerplate.

From firelayer info:
npmGlobalPackages:
@firelayer/cli: 1.0.0
firelayer: Not Found

i'm on node v12.19.0

**Comment by availit** [comment] 2021-01-31 06:22
I got same error on same node version :/ bummer

**Comment by zanderWK** [comment] 2021-02-08 20:17
Same here, log shows the issue is :

 error command sh -c npm install && lerna bootstrap

**Comment by jpntex** [comment] 2021-02-26 00:15
Can you share the content of the file `firelayer-debug.log`? Or check if there is something relevant to the error there? Thanks

**Comment by jpntex** [comment] 2021-08-06 14:17
Closing for now, without the debug log there isn't much I can do, if someone else gets this issue I'll reopen and take a look.

**Closed as completed by jpntex** 2021-08-06 14:17 UTC
Labels: bug

**Comment by knovikov** [comment] 2022-11-19 03:00
```
[fire-wrap | Sat, 19 Nov 2022 02:51:57 GMT]: Error: Failed to list Firebase projects. See firebase-debug.log for more info.
FirebaseError: Failed to list Firebase projects. See firebase-debug.log for more info.
    at getFirebaseProjectPage (/Users/nov/.nvm/versions/node/v16.18.1/lib/node_modules/@firelayer/cli/node_modules/firebase-tools/lib/management/projects.js:258:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.listFirebaseProjects (/Users/nov/.nvm/versions/node/v16.18.1/lib/node_modules/@firelayer/cli/node_modules/firebase-tools/lib/management/projects.js:281:29)
    at async Command.actionFn (/Users/nov/.nvm/versions/node/v16.18.1/lib/node_modules/@firelayer/cli/node_modules/firebase-tools/lib/commands/projects-list.js:50:20)
    at async Object.exports.default (/Users/nov/.nvm/versions/node/v16.18.1/lib/node_modules/@firelayer/cli/dist/helpers/fireWrap.js:9:18)
    at async Object.exports.default (/Users/nov/.nvm/versions/node/v16.18.1/lib/node_modules/@firelayer/cli/dist/helpers/getFirebaseConfig.js:10:22)
    at async Object.exports.default (/Users/nov/.nvm/versions/node/v16.18.1/lib/node_modules/@firelayer/cli/dist/helpers/install.js:26:28)
    at async Init.run (/Users/nov/.nvm/versions/node/v16.18.1/lib/node_modules/@firelayer/cli/dist/commands/init.js:31:13)
    at async Init._run (/Users/nov/.nvm/versions/node/v16.18.1/lib/node_modules/@firelayer/cli/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/Users/nov/.nvm/versions/node/v16.18.1/lib/node_modules/@firelayer/cli/node_modules/@oclif/config/lib/config.js:173:24)
    at async Main.run (/Users/nov/.nvm/versions/node/v16.18.1/lib/node_modules/@firelayer/cli/node_modules/@oclif/command/lib/main.js:28:9)
    at async Main._run (/Users/nov/.nvm/versions/node/v16.18.1/lib/node_modules/@firelayer/cli/node_modules/@oclif/command/lib/command.js:43:20)
[init | Sat, 19 Nov 2022 02:51:57 GMT]: Error: Failed to list Firebase projects. See firebase-debug.log for more info.
FirebaseError: Failed to list Firebase projects. See firebase-debug.log for more info.
    at getFirebaseProjectPage (/Users/nov/.nvm/versions/node/v16.18.1/lib/node_modules/@firelayer/cli/node_modules/firebase-tools/lib/management/projects.js:258:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.listFirebaseProjects (/Users/nov/.nvm/versions/node/v16.18.1/lib/node_modules/@firelayer/cli/node_modules/firebase-tools/lib/management/projects.js:281:29)
    at async Command.actionFn (/Users/nov/.nvm/versions/node/v16.18.1/lib/node_modules/@firelayer/cli/node_modules/firebase-tools/lib/commands/projects-list.js:50:20)
    at async Object.exports.default (/Users/nov/.nvm/versions/node/v16.18.1/lib/node_modules/@firelayer/cli/dist/helpers/fireWrap.js:9:18)
    at async Object.exports.default (/Users/nov/.nvm/versions/node/v16.18.1/lib/node_modules/@firelayer/cli/dist/helpers/getFirebaseConfig.js:10:22)
    at async Object.exports.default (/Users/nov/.nvm/versions/node/v16.18.1/lib/node_modules/@firelayer/cli/dist/helpers/install.js:26:28)
    at async Init.run (/Users/nov/.nvm/versions/node/v16.18.1/lib/node_modules/@firelayer/cli/dist/commands/init.js:31:13)
    at async Init._run (/Users/nov/.nvm/versions/node/v16.18.1/lib/node_modules/@firelayer/cli/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/Users/nov/.nvm/versions/node/v16.18.1/lib/node_modules/@firelayer/cli/node_modules/@oclif/config/lib/config.js:173:24)
    at async Main.run (/Users/nov/.nvm/versions/node/v16.18.1/lib/node_modules/@firelayer/cli/node_modules/@oclif/command/lib/main.js:28:9)
    at async Main._run (/Users/nov/.nvm/versions/node/v16.18.1/lib/node_modules/@firelayer/cli/node_modules/@oclif/command/lib/command.js:43:20)
```

**Comment by knovikov** [comment] 2022-11-19 03:47
Solution:
`firebase login --reauth`
